import type { Feature, GeoJsonProperties, Polygon } from 'geojson'
import { type Campus, type Building, LocationType } from './types'
import { convex } from '@turf/turf'
import {
  AD_BUILDING,
  B_BUILDING,
  BB_BUILDING,
  BH_BUILDING,
  CC_BUILDING,
  CI_BUILDING,
  CJ_BUILDING,
  CL_BUILDING,
  D_BUILDING,
  EN_BUILDING,
  ER_BUILDING,
  EV_BUILDING,
  FA_BUILDING,
  FB_BUILDING,
  FC_BUILDING,
  FG_BUILDING,
  GA_BUILDING,
  GE_BUILDING,
  GM_BUILDING,
  GN_BUILDING,
  GS_BUILDING,
  H_BUILDING,
  HA_BUILDING,
  HB_BUILDING,
  HC_BUILDING,
  HU_BUILDING,
  JR_BUILDING,
  K_BUILDING,
  LB_BUILDING,
  LD_BUILDING,
  LS_BUILDING,
  M_BUILDING,
  MB_BUILDING,
  MI_BUILDING,
  MU_BUILDING,
  P_BUILDING,
  PC_BUILDING,
  PR_BUILDING,
  PS_BUILDING,
  PT_BUILDING,
  PY_BUILDING,
  Q_BUILDING,
  R_BUILDING,
  RA_BUILDING,
  RF_BUILDING,
  RR_BUILDING,
  S_BUILDING,
  SB_BUILDING,
  SC_BUILDING,
  SD_BUILDING,
  SH_BUILDING,
  SI_BUILDING,
  SP_BUILDING,
  T_BUILDING,
  TA_BUILDING,
  TD_BUILDING,
  V_BUILDING,
  VA_BUILDING,
  VE_BUILDING,
  VL_BUILDING,
  X_BUILDING,
  Z_BUILDING,
} from './buildings'
import {
  ccClassrooms,
  cjClassrooms,
  clClassrooms,
  fbClassrooms,
  fgClassrooms,
  hbClassrooms,
  hcClassrooms,
  hClassrooms,
  lsClassrooms,
  mbClassrooms,
  rfClassrooms,
  siClassrooms,
  spClassrooms,
} from './classrooms'

const sgwBuildings: Building[] = [
  TD_BUILDING,
  LS_BUILDING,
  LB_BUILDING,
  H_BUILDING,
  EV_BUILDING,
  MB_BUILDING,
  B_BUILDING,
  CI_BUILDING,
  CL_BUILDING,
  D_BUILDING,
  EN_BUILDING,
  ER_BUILDING,
  FA_BUILDING,
  FB_BUILDING,
  FG_BUILDING,
  GA_BUILDING,
  GM_BUILDING,
  GN_BUILDING,
  GS_BUILDING,
  K_BUILDING,
  LD_BUILDING,
  M_BUILDING,
  MI_BUILDING,
  MU_BUILDING,
  P_BUILDING,
  PR_BUILDING,
  Q_BUILDING,
  R_BUILDING,
  RR_BUILDING,
  S_BUILDING,
  SB_BUILDING,
  T_BUILDING,
  V_BUILDING,
  VA_BUILDING,
  X_BUILDING,
  Z_BUILDING,
]

const loyBuildings: Building[] = [
  VL_BUILDING,
  VE_BUILDING,
  PT_BUILDING,
  PS_BUILDING,
  FC_BUILDING,
  AD_BUILDING,
  CC_BUILDING,
  PY_BUILDING,
  RF_BUILDING,
  SP_BUILDING,
  GE_BUILDING,
  CJ_BUILDING,
  RA_BUILDING,
  PC_BUILDING,
  SD_BUILDING,
  HU_BUILDING,
  HA_BUILDING,
  HB_BUILDING,
  JR_BUILDING,
  SI_BUILDING,
  SC_BUILDING,
  BB_BUILDING,
  SH_BUILDING,
  HC_BUILDING,
  TA_BUILDING,
  BH_BUILDING,
]

const sgwPolygonFeature = convex({
  type: 'GeometryCollection',
  geometries: sgwBuildings.map((building) => building.polygon),
}) as Feature<Polygon, GeoJsonProperties>

export const sgwCampus: Campus = {
  type: LocationType.Campus,
  name: 'Sir George Williams Campus ',
  ref: 'SGW',
  buildings: sgwBuildings,
  polygon: sgwPolygonFeature.geometry,
}

const loyPolygonFeature = convex({
  type: 'GeometryCollection',
  geometries: loyBuildings.map((building) => building.polygon),
}) as Feature<Polygon, GeoJsonProperties>

export const loyCampus: Campus = {
  type: LocationType.Campus,
  name: 'Loyola Campus',
  ref: 'LOY',
  buildings: loyBuildings,
  polygon: loyPolygonFeature.geometry,
}

export const classrooms = [
  ...ccClassrooms,
  ...cjClassrooms,
  ...clClassrooms,
  ...fbClassrooms,
  ...fgClassrooms,
  ...hClassrooms,
  ...hbClassrooms,
  ...hcClassrooms,
  ...lsClassrooms,
  ...mbClassrooms,
  ...rfClassrooms,
  ...siClassrooms,
  ...spClassrooms,
]
export const buildings = [...sgwBuildings, ...loyBuildings]
export const campuses = [sgwCampus, loyCampus]
export const locations = [...buildings, ...campuses, ...classrooms]
export const locationsMap = new Map(
  locations.map((location) => [location.ref, location]),
)
