// These tests were generated by Github Copilot

import { beforeEach, describe, expect, it, vi } from 'vitest'

import type { Location } from '../../src/lib/types'
import { LocationType } from '../../src/lib/types'

type SearchHistoryModule = typeof import('../../src/lib/search-history')

function createLocation(ref: string): Location {
  return {
    type: LocationType.Campus,
    name: `Campus ${ref}`,
    ref,
  }
}

function installLocalStorageMock(initial: Record<string, string> = {}) {
  const store = new Map(Object.entries(initial))

  vi.stubGlobal('localStorage', {
    getItem: (key: string) => store.get(key) ?? null,
    setItem: (key: string, value: string) => {
      store.set(key, value)
    },
    removeItem: (key: string) => {
      store.delete(key)
    },
    clear: () => {
      store.clear()
    },
  })
}

describe('search history', () => {
  let searchHistory: SearchHistoryModule['default']

  beforeEach(async () => {
    vi.resetModules()
    vi.unstubAllGlobals()
    installLocalStorageMock()
    ;({ default: searchHistory } = await import('../../src/lib/search-history'))
  })

  it('starts empty when localStorage has no saved history', () => {
    expect(searchHistory.getHistory()).toEqual([])
  })

  it('adds locations to the front of history', () => {
    const first = createLocation('first')
    const second = createLocation('second')

    searchHistory.push(first)
    searchHistory.push(second)

    expect(searchHistory.getHistory()).toEqual([second, first])
  })

  it('deduplicates by ref and moves latest selection to the front', () => {
    const first = createLocation('shared-ref')
    const sameRefNewName = {
      ...createLocation('shared-ref'),
      name: 'Updated Campus Name',
    }

    searchHistory.push(first)
    searchHistory.push(sameRefNewName)

    expect(searchHistory.getHistory()).toEqual([sameRefNewName])
  })

  it('keeps only the 5 most recent items', () => {
    const locations = ['a', 'b', 'c', 'd', 'e', 'f'].map(createLocation)

    locations.forEach((location) => searchHistory.push(location))

    expect(searchHistory.getHistory()).toEqual([
      locations[5],
      locations[4],
      locations[3],
      locations[2],
      locations[1],
    ])
  })

  it('reports whether a location exists in history', () => {
    const saved = createLocation('known')
    const missing = createLocation('unknown')

    searchHistory.push(saved)

    expect(searchHistory.has(saved)).toBe(true)
    expect(searchHistory.has(missing)).toBe(false)
  })

  it('loads existing history from localStorage on initialization', async () => {
    const seeded = [createLocation('saved-1'), createLocation('saved-2')]

    vi.resetModules()
    vi.unstubAllGlobals()
    installLocalStorageMock({ searchHistory: JSON.stringify(seeded) })
    ;({ default: searchHistory } = await import('../../src/lib/search-history'))

    expect(searchHistory.getHistory()).toEqual(seeded)
  })

  it('returns a copy from getHistory', () => {
    const location = createLocation('immutable')
    searchHistory.push(location)

    const history = searchHistory.getHistory()
    history.push(createLocation('extra'))

    expect(searchHistory.getHistory()).toEqual([location])
  })
})
